# Generated by Django 4.2.10 on 2024-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssid_1', models.FloatField(verbose_name='lv signal 1')),
                ('rssid_2', models.FloatField(verbose_name='lv signal 2')),
                ('rssid_3', models.FloatField(verbose_name='lv signal 3')),
            ],
        ),
    ]
